spring.application.name=agri
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/agri?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

jwt.secret=MySuperSecretKeyForJWT1234567890!@#
jwt.expirationMs=3600000

# Fix for Spring AI Google GenAI startup error (Mandatory even if using Groq)
spring.ai.google.genai.project-id=agri-protect-placeholder
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.api-key=placeholder-key-not-used-for-groq

groq.api.key=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