package tn.esprit.agri.entities.enums;
public enum WalletTransactionType {
    DEPOSIT, WITHDRAWAL, MARKETPLACE_PAYMENT, MARKETPLACE_RECEIPT,
    TRANSFER_TO_EMERGENCY, TRANSFER_FROM_EMERGENCY,
    COMMISSION, REFUND, PEER_TRANSFER_OUT, PEER_TRANSFER_IN
}
